language: python

python:
    - 2.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install -y supercollider
    - sudo apt-get install -y jackd2
    - sudo jackd -m -r -p 32 -d dummy -r 44100 &
    - sleep 1
    - alsa_out -q1 2>&1 > /dev/null &
    - sleep 1

install:
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - python ./supriya/scr/run-supriya-doctests ./supriya

notifications:
    email: false