language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - python ./supriya/scr/run-supriya-doctests ./supriya

notifications:
    email: false