language: python

python:
    - 2.7
    - 3.3
    - 3.4

before_install:
    - sudo add-apt-repository ppa:supercollider/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install supercollider
    - sudo apt-get install -y libasound-dev libjack-jackd2-dev

install:
    - pip install -r requirements.txt
    - pip install -e .
    - sclang -h

script:
    - py.test -rf -vv supriya
    - python ./supriya/scripts/run-supriya-doctests ./supriya
    - make -C supriya/docs/ html

notifications:
    email: false