language: python

sudo: required

python:
  - 3.6

env:
  global:
    AUDIODEV=null

before_install:
- sudo usermod -a -G audio travis
- sudo apt-get update -qq
- sudo apt-get install -y alsa-oss alsa-utils graphviz jackd libasound2-dev libjack-dev libjack0 portaudio19-dev supercollider
- sudo bash tests/prep-dummy-soundcard.sh
- sudo -E su $USER -c "scsynth -h || true"

install:
- pip install -e .

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5 # give xvfb time to start
- sudo -E su $USER -c "jackd -r -ddummy -r44100 -p1024" &
- sleep 5 # give jackd time to start
- sudo -E su $USER -c "scsynth -D 0 -H dummy -R 0 -u 57110" &
- sleep 5
- killall scsynth

script:
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; python -c 'import supriya; supriya.Server().boot(); supriya.Server().quit()'"
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; py.test"

notifications:
    email: false
