language: python

python:
    - 2.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install -y supercollider
    - sudo xvfb-run jackd -m -n TEST -r -d dummy -r 44100 &
    - sleep 5
#    - xvfb-run scsynth -D 0 -H TEST:CLIENT -u 57751 -R 0 &
#    - sleep 5
#    - killall scsynth

script:
#    - python ./supriya/scr/run-supriya-doctests ./supriya
    - pip install -r requirements.txt
    - pip install -e . 
    - make -C supriya/docs/ html

notifications:
    email: false