language: python

python:
    - 2.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz supercollider

install:
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - python ./supriya/scr/run-supriya-doctests ./supriya

notifications:
    email: false