language: python

python:
    - 2.7
    - 3.3
    - 3.4

before_install:

    - sudo apt-get install build-essential
    - sudo apt-get install libasound2-dev

script:
    - pip install -r requirements.txt
    - pip install -e .

notifications:
    email: false
