language: python

python:
    - 2.7, 3.3, 3.4

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install -y supercollider

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - py.test -rf supriya
    - python ./supriya/scr/run-supriya-doctests ./supriya
    - make -C supriya/docs/ html

notifications:
    email: false