language: python

python:
    - 3.5

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install -y pulseaudio pulseaudio-module-jack
    - sudo apt-get install -y libasound-dev libjack-jackd2-dev
    - sudo apt-get install -y supercollider 

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - python -c 'import supriya'

notifications:
    email: false
