language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y supercollider
  - sudo apt-get install -y graphviz
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - supriya/scr/run-supriya-doctests supriya