language: python

sudo: false

addons:
    apt:
        packages:
            build-essential
python:
    - 2.7
    - 3.3
    - 3.4

script:
    - pip install -r requirements.txt
    - pip install -e .

notifications:
    email: false
