language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt  
    - sudo apt-get update -qq
    - sudo apt-get install -y supercollider
    - sudo apt-get install -y graphviz

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - supriya/scr/run-supriya-doctests supriya