name: Publish
on:
  release:
    types: [released]

env:
  SC_ORIGIN: https://github.com/supercollider/supercollider.git
  SC_BRANCH: develop

jobs:
  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --outdir dist/
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  update-gh-pages:
    name: Update gh-pages
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install SuperCollider
      uses: ./.github/actions/supercollider
      with:
        branch: ${{ env.SC_BRANCH }}
        origin: ${{ env.SC_ORIGIN }}
    - name: Install Supriya
      run: pip install -e .[docs,ipython,test]
    - name: Install APT deps
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame
    - name: Build docs
      run: make docs
    - name: Clone gh-pages
      run: git clone --branch gh-pages `git config --get remote.origin.url` gh-pages/
    - name: Rsync docs
      run: rsync -rtv --del --exclude=.git docs/build/html/ gh-pages/
    - name: Touch .nojekyll
      run: touch gh-pages/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        allow_empty_commit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
