name: Build scsynth
on:
  pull_request:
    branches:
    - master
jobs:
  scsynth:
    name: scsynth
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone SC
      run: |
        git clone ${SC_ORIGIN} /tmp/supercollider
        cd /tmp/supercollider
        git checkout ${SC_BRANCH}
        git submodule -q init
        git submodule -q update
        mkdir BUILD
        echo "SC_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SC_ORIGIN_MD5=$(echo ${SC_ORIGIN} | md5sum | head -c 7)" >> $GITHUB_ENV
      env:
        SC_BRANCH: Version-3.10.0
        SC_ORIGIN: https://github.com/supercollider/supercollider.git
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: /tmp/supercollider
        key: supercollider-${{runner.os}}-${{env.SC_ORIGIN_MD5}}-${{env.SC_COMMIT_SHA}}
    - name: Install Deps
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get clean
        sudo apt-get update
        sudo apt-get install --yes \
          build-essential \
          alsa-oss \
          alsa-utils \
          cmake \
          jackd2 \
          libasound2-dev \
          libavahi-client-dev \
          libfftw3-dev \
          libicu-dev \
          libjack-jackd2-dev \
          libudev-dev \
          libreadline6-dev \
          libsndfile1-dev \
          libxt-dev \
          pkg-config
    - name: Build SC
      run: |
        cmake --debug-output -DCMAKE_BUILD_TYPE=Release -DSC_EL=OFF -DSC_IDE=OFF -DSC_QT=OFF /tmp/supercollider > /dev/null
        sudo make install
      working-directory: /tmp/supercollider/BUILD
    - name: Sanity check
      run: |
        scsynth -v
    - name: Setup Jack
      run: |
        sudo usermod -a -G audio ${USER}
        sudo -E su ${USER} -c "jackd -r -ddummy -r44100 -p1024" &
        sleep 5
        sudo -E su $USER -c "scsynth -D 0 -H dummy -R 0 -u 57110" &
        sleep 5
        killall scsynth
