name: Build scsynth
on:
  pull_request:
    branches:
    - master
jobs:
  scsynth:
    name: scsynth
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone SC
      run: |
        git clone ${SC_ORIGIN} /tmp/supercollider
        cd /tmp/supercollider
        git checkout ${SC_BRANCH}
        git submodule -q init
        git submodule -q update
        mkdir BUILD
        echo "SC_CACHE_KEY=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      env:
        SC_BRANCH: Version-3.10.0
        SC_ORIGIN: https://github.com/supercollider/supercollider.git
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: /tmp/supercollider
        key: ${{runner.os}}-${{SC_CACHE_KEY}}
    - name: Install Deps
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get clean
        sudo apt-get update
        sudo apt-get install --yes build-essential cmake pkg-config libjack-jackd2-dev libsndfile1-dev libasound2-dev libavahi-client-dev libreadline6-dev libfftw3-dev libicu-dev libxt-dev libudev-dev
    - name: Build SC
      run: |
        cmake --debug-output -DCMAKE_BUILD_TYPE=Release -DSC_EL=OFF -DSC_IDE=OFF -DSC_QT=OFF /tmp/supercollider > /dev/null
        sudo make install
      working-directory: /tmp/supercollider/BUILD
    - name: Sanity check
      run: |
        scsynth -v
