name: Testing
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
env:
  MYPYPATH: /tmp/typehints
  SC_ORIGIN: https://github.com/josiah-wolf-oberholtzer/supercollider.git
  SC_BRANCH: s-query

jobs:

  cancel:
    name: Cancel previous workflow
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  supercollider:
    name: Build SuperCollider
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SuperCollider
      uses: ./.github/actions/supercollider
      with:
        branch: ${{ env.SC_BRANCH }}
        origin: ${{ env.SC_ORIGIN }}

  install:
    name: Install Supriya
    needs: [cancel]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest]
        include:
        - os: macos-latest
          python-version: "3.10"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Supriya
      run: |
        pip install -e .
    - name: Sanity-check Supriya
      run: |
        python -c "from supriya import Server; print(Server)"
        python -c "from supriya.realtime.shm import ServerSHM; print(ServerSHM)"

  lint:
    name: Lint Supriya
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Supriya
      run: |
        pip install -e .[ipython,test]
    - name: Get Type Hints
      run: |
        pip install --target /tmp/typehints --no-deps uqbar
    - name: Run Black
      run: |
        make black-check
    - name: Run Flake8
      run: |
        make flake8
    - name: Run Mypy
      run: |
        make mypy

  test:
    name: Test Supriya
    needs: [supercollider]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install APT deps
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame
    - name: Install Supriya
      run: |
        pip install -e .[ipython,test]
    - name: Install SuperCollider
      uses: ./.github/actions/supercollider
      with:
        branch: ${{ env.SC_BRANCH }}
        origin: ${{ env.SC_ORIGIN }}
    - name: Sanity-check Supriya
      run: |
        python -c 'import supriya; server = supriya.Server(); server.boot(); server.quit(); exit()'
    - name: Run Pytest
      run: pytest
      timeout-minutes: 15

  docs:
    name: Build docs
    needs: [supercollider]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install APT deps
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame
    - name: Install SuperCollider
      uses: ./.github/actions/supercollider
      with:
        branch: ${{ env.SC_BRANCH }}
        origin: ${{ env.SC_ORIGIN }}
    - name: Install Supriya
      run: |
        pip install -e .[docs,ipython]
    - name: Build docs
      run: make docs
